import type { EnvSet } from "../types";
import { useGrouping } from "./useGrouping";

/** Well-known placeholder mappings for common Laravel keys */
const PLACEHOLDER_MAP: Record<string, string> = {
  APP_NAME: "your_app_name",
  APP_ENV: "local",
  APP_KEY: "",
  APP_DEBUG: "true",
  APP_URL: "http://localhost",
  APP_PORT: "8000",
  APP_LOCALE: "en",
  DB_CONNECTION: "mysql",
  DB_HOST: "127.0.0.1",
  DB_PORT: "3306",
  DB_DATABASE: "your_database",
  DB_USERNAME: "your_database_user",
  DB_PASSWORD: "your_database_password",
  MAIL_MAILER: "smtp",
  MAIL_HOST: "mailpit",
  MAIL_PORT: "1025",
  MAIL_USERNAME: "",
  MAIL_PASSWORD: "",
  MAIL_ENCRYPTION: "",
  MAIL_FROM_ADDRESS: "hello@example.com",
  MAIL_FROM_NAME: "${APP_NAME}",
  REDIS_HOST: "127.0.0.1",
  REDIS_PASSWORD: "",
  REDIS_PORT: "6379",
  CACHE_DRIVER: "file",
  CACHE_STORE: "file",
  QUEUE_CONNECTION: "sync",
  SESSION_DRIVER: "file",
  SESSION_LIFETIME: "120",
  LOG_CHANNEL: "stack",
  LOG_LEVEL: "debug",
  BROADCAST_DRIVER: "log",
  FILESYSTEM_DISK: "local",
  AWS_ACCESS_KEY_ID: "",
  AWS_SECRET_ACCESS_KEY: "",
  AWS_DEFAULT_REGION: "us-east-1",
  AWS_BUCKET: "",
  PUSHER_APP_ID: "",
  PUSHER_APP_KEY: "",
  PUSHER_APP_SECRET: "",
  PUSHER_APP_CLUSTER: "mt1",
  VITE_APP_NAME: "${APP_NAME}",
  VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}",
  VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}",
};

export function useEnvExample() {
  const { SERVICE_PREFIXES } = useGrouping();

  /**
   * Generate a .env.example template from the union of all loaded env sets.
   * Keys are grouped by service prefix with comments indicating which
   * environments define each key.
   */
  function generateEnvExample(sets: EnvSet[]): string {
    if (sets.length === 0) return "# No environment files loaded\n";

    // Collect all keys across all sets
    const allKeys = new Set<string>();
    for (const set of sets) {
      for (const key of Object.keys(set.values)) {
        allKeys.add(key);
      }
    }

    const sortedKeys = [...allKeys].sort();

    // Group keys by prefix
    const groups: Array<{ label: string; prefix: string; keys: string[] }> = [];
    const assignedKeys = new Set<string>();

    for (const { prefix, label } of SERVICE_PREFIXES) {
      const matching = sortedKeys.filter((k) => k.startsWith(prefix));
      if (matching.length === 0) continue;
      groups.push({ label, prefix, keys: matching });
      for (const k of matching) assignedKeys.add(k);
    }

    // Ungrouped keys
    const ungrouped = sortedKeys.filter((k) => !assignedKeys.has(k));
    if (ungrouped.length > 0) {
      groups.push({ label: "Other", prefix: "", keys: ungrouped });
    }

    // Build the output
    const lines: string[] = [
      `# .env.example`,
      `# Generated by Drift on ${new Date().toLocaleDateString("en-GB")}`,
      `# Union of ${sets.length} environment file${sets.length !== 1 ? "s" : ""}: ${sets.map((s) => s.name).join(", ")}`,
      "",
    ];

    for (const group of groups) {
      lines.push(`# ── ${group.label} ──`);

      for (const key of group.keys) {
        // Comment showing which envs define this key
        const definedIn = sets
          .filter((s) => s.values[key] !== undefined)
          .map((s) => s.name);

        if (definedIn.length < sets.length) {
          const missingFrom = sets
            .filter((s) => s.values[key] === undefined)
            .map((s) => s.name);
          lines.push(`# Defined in: ${definedIn.join(", ")} (missing from: ${missingFrom.join(", ")})`);
        }

        // Use placeholder value
        const placeholder = getPlaceholder(key, sets);
        lines.push(`${key}=${placeholder}`);
      }

      lines.push("");
    }

    return lines.join("\n");
  }

  function getPlaceholder(key: string, sets: EnvSet[]): string {
    // Check well-known placeholders first
    if (key in PLACEHOLDER_MAP) {
      return PLACEHOLDER_MAP[key];
    }

    // For secret-like keys, use empty string
    if (/_SECRET$/i.test(key) || /_PASSWORD$/i.test(key) || /_TOKEN$/i.test(key) || /_KEY$/i.test(key)) {
      return "";
    }

    // For URL-like keys, use a descriptive placeholder
    if (key.endsWith("_URL")) {
      return "https://example.com";
    }

    // For boolean-like keys, use the most common value across sets
    const values = sets
      .map((s) => s.values[key])
      .filter((v): v is string => v !== undefined);

    if (values.length > 0) {
      const lower = values[0].toLowerCase();
      if (["true", "false", "yes", "no", "0", "1"].includes(lower)) {
        return values[0];
      }
    }

    // Default: descriptive placeholder from key name
    const descriptive = key
      .toLowerCase()
      .replace(/_/g, "_")
      .replace(/^(app|db|mail|aws|redis|cache|queue|session|log|broadcast)_/i, "your_");

    if (descriptive !== key.toLowerCase()) {
      return descriptive;
    }

    return "";
  }

  return {
    generateEnvExample,
  };
}
