import { computed } from "vue";
import { useChangeHistory } from "./useChangeHistory";
import { useMasking } from "./useMasking";

/**
 * Generates a Markdown summary of env drift resolution changes from the current
 * session's change history. Secret values are masked in the output.
 */
export function useResolutionSummary() {
  const { history } = useChangeHistory();
  const { isSensitiveKey } = useMasking();

  /** Session start timestamp — changes before the current page load are excluded */
  const sessionStart = Date.now();

  const sessionChanges = computed(() =>
    history.value.filter((e) => e.timestamp >= sessionStart),
  );

  const hasSessionChanges = computed(() => sessionChanges.value.length > 0);

  function maskIfSensitive(key: string, value: string | undefined): string {
    if (value === undefined) return "(missing)";
    if (!value) return "(empty)";
    if (isSensitiveKey(key)) return "••••••••";
    return value;
  }

  function generateMarkdown(): string {
    const changes = sessionChanges.value;
    if (changes.length === 0) return "";

    const now = new Date();
    const timestamp = now.toISOString().replace("T", " ").slice(0, 19);

    // Group changes by env file
    const byFile = new Map<string, typeof changes>();
    for (const entry of changes) {
      const key = entry.envSetName;
      if (!byFile.has(key)) byFile.set(key, []);
      byFile.get(key)!.push(entry);
    }

    const lines: string[] = [
      `## Drift Resolution Summary`,
      ``,
      `**Date:** ${timestamp}`,
      `**Changes:** ${changes.length} key${changes.length === 1 ? "" : "s"} across ${byFile.size} environment${byFile.size === 1 ? "" : "s"}`,
      ``,
    ];

    for (const [envName, entries] of byFile) {
      lines.push(`### ${envName}`);
      lines.push(``);
      lines.push(`| Key | Previous | New | Action |`);
      lines.push(`|-----|----------|-----|--------|`);

      // Deduplicate: keep only the latest change per key
      const latest = new Map<string, (typeof entries)[0]>();
      for (const entry of [...entries].reverse()) {
        latest.set(entry.key, entry);
      }

      for (const entry of latest.values()) {
        const prev = maskIfSensitive(entry.key, entry.previousValue);
        const next = maskIfSensitive(entry.key, entry.newValue);
        const action = entry.previousValue === undefined ? "Added" : "Updated";
        lines.push(`| \`${entry.key}\` | ${prev} | ${next} | ${action} |`);
      }

      lines.push(``);
    }

    lines.push(`---`);
    lines.push(`*Generated by Drift*`);

    return lines.join("\n");
  }

  return {
    hasSessionChanges,
    sessionChanges,
    generateMarkdown,
  };
}
